au! BufRead,BufNewFile Gemfile setf ruby
au! BufRead,BufNewFile Capfile setf ruby
au! BufRead,BufNewFile Vagrantfile setf ruby
au! BufRead,BufNewFile Cheffile setf ruby
au! BufRead,BufNewFile Berksfile setf ruby
au! BufRead,BufNewFile .pryrc setf ruby
au! BufRead,BufNewFile *.cap setf ruby
au! BufRead,BufNewFile *.md setf markdown
au! BufRead,BufNewFile *.psgi setf perl
